, "?"
, "Agricultural Freeze"
, "Astronomical High Tide"        
, "Astronomical Low Tide"
, "Avalanche"
, "Black Ice"                     
, "Blizzard"
, "Blowing Snow"
, "Breakup Flooding"              
, "Brush Fire"
, "Coastal Erosion"
, "Coastal Flood"                 
, "Coastal Flooding"
, "Coastal Flooding/Erosion"
, "Coastal Storm"                 
, "Cold Air Tornado"
, "Cold And Snow"                 
, "Cold And Wet Conditions"
, "Cold Temperature"
, "Cold Wave"                     
, "Cold Weather"
, "Cold"
, "Cold/Wind Chill"
, "Cold/Winds"                    
, "Dam Break"
, "Damaging Freeze"
, "Dense Fog"                     
, "Dense Smoke"
, "Downburst"
, "Drought"                       
, "Drought/Excessive Heat"
, "Drowning"
, "Dry Microburst"                
, "Dry Mircoburst Winds"
, "Dust Devil Waterspout"         
, "Dust Devil"
, "Dust Storm"
, "Dust Storm/High Winds"
, "Erosion/Cstl Flood"            
, "Excessive Heat"
, "Excessive Rainfall"
, "Excessive Snow"                
, "Excessive Wetness"
, "Extended Cold"
, "Extreme Cold"                  
, "Extreme Cold/Wind Chill"
, "Extreme Heat"
, "Extreme Wind Chill"            
, "Extreme Windchill"
, "Falling Snow/Ice"
, "Flash Flood - Heavy Rain"
, "Flash Flood From Ice Jams"
, "Flash Flood Winds"             
, "Flash Flood"                   
, "Flash Flood/ Street"
, "Flash Flood/Landslide"
, "Flash Flooding"                
, "Flash Flooding/Thunderstorm Wi"
, "Flash Floods"
, "Flood & Heavy Rain"
, "Flood"                         
, "Flood/Flash Flood"
, "Flood/Rain/Winds"              
, "Flooding"
, "Flooding/Heavy Rain"
, "Floods"                        
, "Fog And Cold Temperatures"
, "Fog"
, "Forest Fires"                  
, "Freeze"
, "Freezing Drizzle"
, "Freezing Fog"                  
, "Freezing Rain"
, "Freezing Rain/Snow"
, "Freezing Spray"                
, "Frost/Freeze"
, "Funnel Cloud"
, "Glaze Ice"
, "Glaze"                         
, "Glaze/Ice Storm"
, "Gradient Wind"                 
, "Grass Fires"
, "Gustnado"
, "Gusty Wind"                    
, "Gusty Wind/Hail"
, "Gusty Wind/Rain"
, "Gusty Winds"                   
, "Hail 125"
, "Hail 175"                      
, "Hail 200"
, "Hail 275"
, "Hail 450"                      
, "Hail 75"
, "Hail"
, "Hail/Wind"
, "Hail/Winds"                    
, "Hard Freeze"
, "Hazardous Surf"
, "Heat Wave Drought"
, "Heat Wave"
, "Heat Waves"                    
, "Heat"                          
, "Heavy Lake Snow"
, "Heavy Mix"
, "Heavy Rain And Flood"
, "Heavy Rain"                    
, "Heavy Rain/High Surf"
, "Heavy Rain/Severe Weather"     
, "Heavy Rain/Small Stream Urban"
, "Heavy Rain/Snow"
, "Heavy Rains"                   
, "Heavy Rains/Flooding"
, "Heavy Seas"
, "Heavy Shower"                  
, "Heavy Snow And High Winds"     
, "Heavy Snow And Strong Winds"
, "Heavy Snow Squalls"
, "Heavy Snow"
, "Heavy Snow-Squalls"
, "Heavy Snow/Blizzard/Avalanche" 
, "Heavy Snow/High Winds & Flood"
, "Heavy Snow/Squalls"
, "Heavy Snowpack"                
, "Heavy Surf And Wind"
, "Heavy Surf Coastal Flooding"   
, "Heavy Surf"
, "Heavy Surf/High Surf"
, "Heavy Swells"
, "High Seas"                     
, "High Surf Advisory"
, "High Surf"
, "High Swells"                   
, "High Tides"
, "High Water"
, "High Wind (G40)"
, "High Wind Damage"
, "High Wind"                     
, "High Winds"                    
, "High Winds/Coastal Flood"
, "High Winds/Cold"
, "Hurricane Edouard"
, "Hurricane Erin"
, "Hurricane Opal"                
, "Hurricane Opal/High Winds"
, "Hurricane"                     
, "Hurricane/Typhoon"
, "Hvy Rain"                      
, "Hyperthermia/Exposure"
, "Hypothermia"
, "Hypothermia/Exposure"          
, "Ice Jam Flooding"
, "Ice Roads"                     
, "Ice Storm"
, "Ice Storm/Flash Flood"
, "Ice"
, "Ice/Strong Winds"              
, "Icy Roads"
, "Lake Effect Snow"              
, "Lake-Effect Snow"
, "Lakeshore Flood"
, "Landslide"
, "Landslides"                    
, "Landspout"
, "Late Season Snow"
, "Light Freezing Rain"           
, "Light Snow"
, "Light Snowfall"
, "Lighting"                      
, "Lightning And Heavy Rain"
, "Lightning And Thunderstorm Win"
, "Lightning Fire"
, "Lightning Injury"
, "Lightning Thunderstorm Winds"  
, "Lightning"
, "Lightning."
, "Ligntning"
, "Low Temperature"               
, "Marine Accident"
, "Marine High Wind"
, "Marine Strong Wind"            
, "Marine Thunderstorm Wind"
, "Marine Tstm Wind"
, "Microburst"                    
, "Mixed Precip"
, "Mixed Precipitation"
, "Mud Slide"                     
, "Mud Slides"
, "Mudslide"
, "Mudslides"                     
, "Non Tstm Wind"
, "Non-Severe Wind Damage"
, "Other"                         
, "Rain"
, "Rain/Snow"
, "Rain/Wind"                     
, "Record Cold"
, "Record Heat"
, "Record/Excessive Heat"         
, "Rip Current"
, "Rip Currents"
, "Rip Currents/Heavy Surf"       
, "River And Stream Flood"
, "River Flood"
, "River Flooding"                
, "Rock Slide"
, "Rogue Wave"
, "Rough Seas"                    
, "Rough Surf"
, "Seiche"
, "Severe Thunderstorm"           
, "Severe Thunderstorms"
, "Sleet/Ice Storm"
, "Small Hail"                    
, "Snow Accumulation"
, "Snow And Ice"                  
, "Snow Freezing Rain"
, "Snow Squall"
, "Snow Squalls"                  
, "Snow"
, "Snow/ Bitter Cold"
, "Snow/ Ice"
, "Snow/Heavy Snow"               
, "Snow/High Winds"
, "Snow/Ice Storm"
, "Snow/Sleet"                    
, "Snow/Sleet/Freezing Rain"
, "Snowmelt Flooding"
, "Storm Force Winds"             
, "Storm Surge"
, "Storm Surge/Tide"
, "Strong Wind"                   
, "Strong Winds"
, "Thundeerstorm Winds"
, "Thunderestorm Winds"           
, "Thundersnow"
, "Thunderstorm  Winds"           
, "Thunderstorm Damage To"
, "Thunderstorm Wind 60 Mph"      
, "Thunderstorm Wind 65 Mph"
, "Thunderstorm Wind 65Mph"
, "Thunderstorm Wind 98 Mph"      
, "Thunderstorm Wind G52"
, "Thunderstorm Wind G60"
, "Thunderstorm Wind"
, "Thunderstorm Wind."            
, "Thunderstorm Wind/ Tree"
, "Thunderstorm Wind/ Trees"
, "Thunderstorm Wind/Awning"      
, "Thunderstorm Wind/Lightning"
, "Thunderstorm Winds 13"         
, "Thunderstorm Winds 63 Mph"
, "Thunderstorm Winds And"
, "Thunderstorm Winds G60"        
, "Thunderstorm Winds Hail"
, "Thunderstorm Winds Lightning"
, "Thunderstorm Winds"
, "Thunderstorm Winds/ Flood"     
, "Thunderstorm Winds/Funnel Clou"
, "Thunderstorm Winds/Hail"
, "Thunderstorm Windss"           
, "Thunderstorm Wins"
, "Thunderstorm"
, "Thunderstorms Wind"
, "Thunderstorms Winds"           
, "Thunderstormw"
, "Thunderstrom Wind"
, "Thundertorm Winds"             
, "Thunerstorm Winds"
, "Tidal Flooding"
, "Tornado F0"
, "Tornado F2"
, "Tornado F3"                    
, "Tornado"                       
, "Tornadoes"
, "Torrential Rainfall"
, "Tropical Depression"           
, "Tropical Storm Alberto"
, "Tropical Storm Gordon"         
, "Tropical Storm Jerry"
, "Tropical Storm"
, "Tstm Wind  (G45)"              
, "Tstm Wind (G40)"
, "Tstm Wind (G45)"
, "Tstm Wind 40"                  
, "Tstm Wind 45"
, "Tstm Wind 55"
, "Tstm Wind And Lightning"       
, "Tstm Wind G58"
, "Tstm Wind"
, "Tstm Wind/Hail"
, "Tstm Winds"                    
, "Tstmw"
, "Tsunami"
, "Tunderstorm Wind"              
, "Typhoon"
, "Unseasonable Cold"
, "Unseasonably Cold"             
, "Unseasonably Warm And Dry"
, "Unseasonably Warm"
, "Unseasonal Rain"               
, "Urban And Small Stream Floodin"
, "Urban Flood"
, "Urban Flooding"                
, "Urban Floods"
, "Urban Small"
, "Urban/Small Stream Flood"      
, "Urban/Sml Stream Fld"
, "Warm Weather"
, "Waterspout"                    
, "Waterspout-"
, "Waterspout/ Tornado"
, "Waterspout/Tornado"            
, "Wet Microburst"
, "Whirlwind"
, "Wild Fires"                    
, "Wild/Forest Fire"
, "Wild/Forest Fires"
, "Wildfire"                      
, "Wildfires"
, "Wind Damage"                   
, "Wind Storm"
, "Wind"
, "Wind/Hail"
, "Winds"                         
, "Winter Storm High Winds"
, "Winter Storm"
, "Winter Weather Mix"
, "Winter Weather"                
, "Winter Weather/Mix"
, "Wintry Mix" 